<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Site-Wide Audit Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 9pt; color: #1e293b; }
        .header { text-align: center; margin-bottom: 20px; padding-bottom: 15px; border-bottom: 2px solid #4f46e5; }
        .header h1 { font-size: 18pt; color: #4f46e5; margin-bottom: 5px; }
        .header p { font-size: 9pt; color: #64748b; }
        .meta { margin-bottom: 15px; padding: 10px; background: #f1f5f9; border-radius: 4px; }
        .meta-row { display: flex; justify-content: space-between; margin-bottom: 5px; font-size: 8pt; }
        .meta-label { font-weight: bold; color: #475569; }
        .meta-value { color: #1e293b; }
        .section { margin-bottom: 20px; }
        .section-title { font-size: 11pt; font-weight: bold; color: #1e293b; margin-bottom: 10px; padding-bottom: 5px; border-bottom: 1px solid #e2e8f0; }
        table { width: 100%; border-collapse: collapse; font-size: 8pt; margin-bottom: 15px; }
        th { background: #f1f5f9; color: #475569; font-weight: 600; text-align: left; padding: 6px 8px; border-bottom: 1px solid #cbd5e1; }
        td { padding: 5px 8px; border-bottom: 1px solid #e2e8f0; vertical-align: top; }
        tr:nth-child(even) td { background: #f8fafc; }
        .badge { display: inline-block; padding: 2px 6px; border-radius: 3px; font-size: 7pt; font-weight: 600; }
        .badge-indigo { background: #e0e7ff; color: #4338ca; }
        .badge-amber { background: #fef3c7; color: #92400e; }
        .badge-slate { background: #f1f5f9; color: #475569; }
        .text-sm { font-size: 7pt; color: #64748b; }
        .no-data { text-align: center; padding: 30px; color: #94a3b8; font-size: 9pt; }
        .footer { position: fixed; bottom: 0; left: 0; right: 0; text-align: center; font-size: 7pt; color: #94a3b8; padding: 10px; border-top: 1px solid #e2e8f0; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Site-Wide Audit Report</h1>
        <p>{{ $selectedCompany->company_name ?? 'All Companies' }}</p>
    </div>

    <div class="meta">
        <div class="meta-row">
            <span><span class="meta-label">Report Period:</span> <span class="meta-value">{{ $startDate }} to {{ $endDate }}</span></span>
            <span><span class="meta-label">Generated:</span> <span class="meta-value">{{ now()->format('F d, Y h:i A') }}</span></span>
        </div>
        <div class="meta-row">
            <span><span class="meta-label">Generated By:</span> <span class="meta-value">{{ auth()->user()->first_name }} {{ auth()->user()->last_name }}</span></span>
            <span><span class="meta-label">Scope:</span> <span class="meta-value">{{ $selectedCompany->company_name ?? 'Site-Wide' }}</span></span>
        </div>
    </div>

    @if($auditData)
        {{-- Audit Logs --}}
        @if($auditData['audit_logs']->count())
        <div class="section">
            <div class="section-title">Audit Logs ({{ $auditData['audit_logs']->count() }})</div>
            <table>
                <thead>
                    <tr>
                        <th width="12%">Date</th>
                        <th width="18%">User</th>
                        <th width="15%">Action</th>
                        <th width="25%">Document</th>
                        <th width="30%">Details</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($auditData['audit_logs'] as $log)
                    <tr>
                        <td class="text-sm">{{ $log->created_at->format('M d, Y H:i') }}</td>
                        <td>{{ $log->user ? $log->user->first_name . ' ' . $log->user->last_name : 'System' }}</td>
                        <td><span class="badge badge-indigo">{{ $log->action ?? 'N/A' }}</span></td>
                        <td>{{ $log->document->title ?? 'N/A' }}</td>
                        <td class="text-sm">{{ Str::limit($log->details ?? '-', 50) }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        @endif

        {{-- Uploaded Documents --}}
        @if($auditData['uploaded_documents']->count())
        <div class="section">
            <div class="section-title">Uploaded Documents ({{ $auditData['uploaded_documents']->count() }})</div>
            <table>
                <thead>
                    <tr>
                        <th width="12%">Date</th>
                        <th width="30%">Title</th>
                        <th width="20%">Uploader</th>
                        <th width="15%">Status</th>
                        <th width="23%">Tracking #</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($auditData['uploaded_documents'] as $doc)
                    <tr>
                        <td class="text-sm">{{ $doc->created_at->format('M d, Y') }}</td>
                        <td>{{ Str::limit($doc->title, 40) }}</td>
                        <td>{{ $doc->user ? $doc->user->first_name . ' ' . $doc->user->last_name : 'N/A' }}</td>
                        <td><span class="badge badge-slate">{{ $doc->status->status ?? 'N/A' }}</span></td>
                        <td class="text-sm">{{ $doc->trackingNumber->tracking_number ?? '-' }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        @endif

        {{-- Workflows --}}
        @if($auditData['workflows']->count())
        <div class="section">
            <div class="section-title">Document Workflows ({{ $auditData['workflows']->count() }})</div>
            <table>
                <thead>
                    <tr>
                        <th width="12%">Date</th>
                        <th width="28%">Document</th>
                        <th width="20%">Sender</th>
                        <th width="20%">Recipient</th>
                        <th width="20%">Status</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($auditData['workflows'] as $wf)
                    <tr>
                        <td class="text-sm">{{ $wf->created_at->format('M d, Y H:i') }}</td>
                        <td>{{ Str::limit($wf->document->title ?? 'N/A', 35) }}</td>
                        <td>{{ $wf->sender ? $wf->sender->first_name . ' ' . $wf->sender->last_name : 'N/A' }}</td>
                        <td>{{ $wf->recipient ? $wf->recipient->first_name . ' ' . $wf->recipient->last_name : 'N/A' }}</td>
                        <td><span class="badge badge-amber">{{ $wf->status ?? 'N/A' }}</span></td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        @endif
    @else
        <div class="no-data">
            No audit data available for the selected criteria.
        </div>
    @endif

    <div class="footer">
        DocTrack © {{ date('Y') }} | Site-Wide Audit Report
    </div>
</body>
</html>
