<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Super Admin Dashboard Report</title>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 11px; color: #1e293b; margin: 0; padding: 20px; }
        h1 { font-size: 22px; color: #1e293b; margin-bottom: 2px; }
        h2 { font-size: 14px; color: #334155; margin-top: 20px; margin-bottom: 8px; border-bottom: 2px solid #e2e8f0; padding-bottom: 4px; }
        .subtitle { font-size: 11px; color: #64748b; margin-bottom: 20px; }
        .kpi-grid { display: table; width: 100%; margin-bottom: 20px; }
        .kpi-cell { display: table-cell; width: 25%; padding: 10px; text-align: center; border: 1px solid #e2e8f0; background: #f8fafc; }
        .kpi-value { font-size: 22px; font-weight: bold; color: #1e293b; }
        .kpi-label { font-size: 9px; color: #64748b; text-transform: uppercase; letter-spacing: 0.5px; margin-top: 2px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 15px; font-size: 10px; }
        th { background: #f1f5f9; color: #475569; padding: 6px 8px; text-align: left; font-size: 9px; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 2px solid #e2e8f0; }
        td { padding: 5px 8px; border-bottom: 1px solid #f1f5f9; }
        tr:nth-child(even) { background: #fafbfc; }
        .text-right { text-align: right; }
        .badge { display: inline-block; padding: 2px 6px; border-radius: 3px; font-size: 9px; font-weight: 600; }
        .badge-green { background: #dcfce7; color: #166534; }
        .badge-red { background: #fee2e2; color: #991b1b; }
        .footer { margin-top: 30px; padding-top: 10px; border-top: 1px solid #e2e8f0; font-size: 9px; color: #94a3b8; text-align: center; }
        .page-break { page-break-before: always; }
    </style>
</head>
<body>
    <h1>Super Admin Dashboard Report</h1>
    <div class="subtitle">Generated by {{ $generatedBy }} on {{ $generatedAt }}</div>

    {{-- KPI Summary --}}
    <div class="kpi-grid">
        <div class="kpi-cell">
            <div class="kpi-value">{{ number_format($totalCompanies) }}</div>
            <div class="kpi-label">Total Companies</div>
        </div>
        <div class="kpi-cell">
            <div class="kpi-value">{{ number_format($totalUsers) }}</div>
            <div class="kpi-label">Total Users</div>
        </div>
        <div class="kpi-cell">
            <div class="kpi-value">{{ number_format($totalDocuments) }}</div>
            <div class="kpi-label">Total Documents</div>
        </div>
        <div class="kpi-cell">
            <div class="kpi-value">{{ number_format($activeSubscriptions) }}</div>
            <div class="kpi-label">Active Subscriptions</div>
        </div>
    </div>

    <div class="kpi-grid">
        <div class="kpi-cell">
            <div class="kpi-value">P{{ number_format($totalRevenue, 2) }}</div>
            <div class="kpi-label">Total Revenue</div>
        </div>
        <div class="kpi-cell">
            <div class="kpi-value">P{{ number_format($mrr, 2) }}</div>
            <div class="kpi-label">Monthly Recurring Revenue</div>
        </div>
        <div class="kpi-cell" colspan="2"></div>
    </div>

    {{-- Monthly Trends --}}
    <h2>Monthly Trends (12 Months)</h2>
    <table>
        <thead>
            <tr>
                <th>Month</th>
                <th class="text-right">Companies</th>
                <th class="text-right">Users</th>
                <th class="text-right">Documents</th>
                <th class="text-right">Subscriptions</th>
                <th class="text-right">Revenue</th>
            </tr>
        </thead>
        <tbody>
            @foreach($monthlyStats['labels'] as $i => $label)
            <tr>
                <td>{{ $label }}</td>
                <td class="text-right">{{ $monthlyStats['companiesData'][$i] }}</td>
                <td class="text-right">{{ $monthlyStats['usersData'][$i] }}</td>
                <td class="text-right">{{ $monthlyStats['documentsData'][$i] }}</td>
                <td class="text-right">{{ $monthlyStats['subscriptionsData'][$i] }}</td>
                <td class="text-right">P{{ number_format($monthlyStats['revenueData'][$i], 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    {{-- Top Companies by Users --}}
    <h2>Top Companies by Users</h2>
    <table>
        <thead>
            <tr><th>Company</th><th class="text-right">Users</th></tr>
        </thead>
        <tbody>
            @foreach($topCompaniesByUsers as $c)
            <tr><td>{{ $c->company_name }}</td><td class="text-right">{{ $c->employees_count }}</td></tr>
            @endforeach
        </tbody>
    </table>

    {{-- Top Companies by Documents --}}
    <h2>Top Companies by Documents</h2>
    <table>
        <thead>
            <tr><th>Company</th><th class="text-right">Documents</th></tr>
        </thead>
        <tbody>
            @foreach($topCompaniesByDocs as $c)
            <tr><td>{{ $c->company_name }}</td><td class="text-right">{{ $c->documents_count }}</td></tr>
            @endforeach
        </tbody>
    </table>

    {{-- Expiring Subscriptions --}}
    @if($expiringSubscriptions->count())
    <h2>Expiring Subscriptions (Next 30 Days)</h2>
    <table>
        <thead>
            <tr><th>Company</th><th>Plan</th><th>Expires</th></tr>
        </thead>
        <tbody>
            @foreach($expiringSubscriptions as $sub)
            <tr>
                <td>{{ $sub->company->company_name ?? 'N/A' }}</td>
                <td>{{ $sub->plan->plan_name ?? 'N/A' }}</td>
                <td><span class="badge badge-red">{{ \Carbon\Carbon::parse($sub->end_date)->format('M d, Y') }}</span></td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    <div class="footer">
        DocTrack &mdash; Super Admin Dashboard Report &mdash; {{ $generatedAt }}
    </div>
</body>
</html>
