<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Analytics Report</title>
    <style>
        @page {
            size: A4 landscape;
            margin: 16mm 14mm;
        }
        body {
            font-family: 'DejaVu Sans', sans-serif;
            padding: 0;
            color: #333;
        }
        h1, h2, h3 {
            color: {{ $companyColor }};
        }
        .header {
            border-bottom: 2px solid {{ $companyColor }};
            padding-bottom: 12px;
            margin-bottom: 20px;
            display: table;
            width: 100%;
        }
        .header-logo {
            display: table-cell;
            vertical-align: middle;
            width: 120px;
        }
        .header-logo img {
            max-height: 50px;
            max-width: 110px;
        }
        .header-title {
            display: table-cell;
            vertical-align: middle;
        }
        .header-title h1 {
            margin: 0;
            font-size: 22px;
        }
        .header-title .company-sub {
            font-size: 12px;
            color: #6b7280;
            margin-top: 2px;
        }
        .report-meta {
            font-size: 0.85em;
            color: #6b7280;
            margin-bottom: 16px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        th, td {
            border: 1px solid #e5e7eb;
            padding: 10px;
            text-align: left;
        }
        th {
            background-color: {{ $companyColor }};
            color: #ffffff;
            font-weight: bold;
        }
        .metrics-table {
            width: 100%;
            border: 1px solid #e5e7eb;
            border-radius: 6px;
            margin-bottom: 18px;
        }
        .metrics-table td {
            padding: 10px 12px;
            border: 1px solid #e5e7eb;
        }
        .metric-label {
            font-size: 0.8em;
            color: #6b7280;
            text-transform: uppercase;
            letter-spacing: 0.04em;
        }
        .metric-value {
            font-size: 1.1em;
            font-weight: bold;
            color: {{ $companyColor }};
            margin-top: 4px;
        }
        .charts-grid {
            width: 100%;
            border: 1px solid #e5e7eb;
            border-radius: 8px;
            padding: 12px;
            margin-bottom: 20px;
        }
        .chart-title {
            font-size: 0.95em;
            font-weight: bold;
            color: #1f2937;
            margin-bottom: 6px;
        }
        .chart-img {
            width: 100%;
            height: auto;
        }
        .charts-row {
            width: 100%;
        }
        .charts-row td {
            vertical-align: top;
            padding: 8px;
        }
        .footer {
            margin-top: 30px;
            font-size: 0.8em;
            color: #6b7280;
            text-align: center;
            border-top: 1px solid #e5e7eb;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="header-logo">
            @if(!empty($logoDataUri))
                <img src="{{ $logoDataUri }}" alt="Logo">
            @endif
        </div>
        <div class="header-title">
            <h1>Analytics Report</h1>
            <div class="company-sub">{{ $companyName }}</div>
        </div>
    </div>

    <div class="report-meta">
        <p><strong>Period:</strong> {{ $startDate }} to {{ $endDate }}</p>
        @if($userDetails)
            <p><strong>User:</strong> {{ $userDetails->name }}</p>
        @endif
        @if($officeDetails)
            <p><strong>Office:</strong> {{ $officeDetails->name }}</p>
        @endif
        <p><strong>Generated at:</strong> {{ $generatedAt }}</p>
        <p><strong>Generated by:</strong> {{ $generatedBy }}</p>
    </div>

    <h2>Summary Metrics</h2>
    <table class="metrics-table">
        <tr>
            <td>
                <div class="metric-label">Average Time to Receive</div>
                <div class="metric-value">{{ $averageTimeToReceive }}</div>
            </td>
            <td>
                <div class="metric-label">Average Time to Review</div>
                <div class="metric-value">{{ $averageTimeToReview }}</div>
            </td>
            <td>
                <div class="metric-label">Documents Forwarded</div>
                <div class="metric-value">{{ $averageDocsForwarded }}</div>
            </td>
            <td>
                <div class="metric-label">Documents Uploaded</div>
                <div class="metric-value">{{ $documentsUploaded }}</div>
            </td>
        </tr>
    </table>

    @if(!empty($charts))
    <div class="charts-grid">
        <div class="chart-title">Monthly Trends</div>
        <img class="chart-img" src="{{ $charts['monthlyTrends'] }}" alt="Monthly trends chart">
    </div>

    <table class="charts-row">
        <tr>
            <td style="width: 66%;">
                <div class="charts-grid">
                    <div class="chart-title">Processing Times</div>
                    <img class="chart-img" src="{{ $charts['processingTimes'] }}" alt="Processing times chart">
                </div>
            </td>
            <td style="width: 34%;">
                <div class="charts-grid">
                    <div class="chart-title">Document Distribution</div>
                    <img class="chart-img" src="{{ $charts['distribution'] }}" alt="Document distribution chart">
                </div>
            </td>
        </tr>
    </table>
    @endif

    <h2>Monthly Trends (Table)</h2>
    <table>
        <thead>
            <tr>
                <th>Month</th>
                <th>Avg. Time to Receive</th>
                <th>Avg. Time to Review</th>
                <th>Docs Forwarded</th>
                <th>Docs Uploaded</th>
            </tr>
        </thead>
        <tbody>
            @foreach($monthlyData as $month => $data)
            <tr>
                <td>{{ $month }}</td>
                <td>{{ $data['receive_time'] }}</td>
                <td>{{ $data['review_time'] }}</td>
                <td>{{ $data['docs_forwarded'] }}</td>
                <td>{{ $data['docs_uploaded'] }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Document Archive System &copy; {{ date('Y') }} - All Rights Reserved</p>
    </div>
</body>
</html>
