<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $office->name }} – Office Dashboard Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', Arial, sans-serif;
            color: #333;
            line-height: 1.5;
            margin: 0;
            padding: 0;
        }
        .container { width: 100%; padding: 20px; }
        .header {
            border-bottom: 2px solid {{ $companyColor }};
            padding-bottom: 15px;
            margin-bottom: 25px;
            display: table;
            width: 100%;
        }
        .header-logo {
            display: table-cell;
            vertical-align: middle;
            width: 120px;
        }
        .header-logo img { max-height: 50px; max-width: 110px; }
        .header-info { display: table-cell; vertical-align: middle; }
        .office-name {
            font-size: 22px;
            font-weight: bold;
            color: {{ $companyColor }};
        }
        .report-meta { color: #6b7280; font-size: 13px; margin: 3px 0; }
        .section { margin-bottom: 28px; }
        .section-title {
            font-size: 16px;
            font-weight: bold;
            margin-bottom: 12px;
            color: {{ $companyColor }};
            border-bottom: 1px solid {{ $companyColor }};
            padding-bottom: 4px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 10px 0 16px 0;
            font-size: 12px;
        }
        table, th, td { border: 1px solid #d1d5db; }
        th {
            background-color: {{ $companyColor }};
            color: #ffffff;
            font-weight: bold;
            text-align: left;
            padding: 7px 10px;
        }
        td { padding: 7px 10px; vertical-align: top; }
        tr:nth-child(even) { background-color: #f9fafb; }
        .metrics-grid { display: table; width: 100%; margin-bottom: 20px; }
        .metric-cell { display: table-cell; width: 25%; padding: 0 8px 0 0; }
        .metric-box {
            background-color: #f3f4f6;
            border-left: 4px solid {{ $companyColor }};
            border-radius: 6px;
            padding: 12px;
        }
        .metric-label { font-size: 12px; color: #6b7280; margin-bottom: 4px; }
        .metric-value { font-size: 20px; font-weight: bold; color: {{ $companyColor }}; }
        .footer {
            text-align: center;
            margin-top: 30px;
            padding-top: 12px;
            border-top: 1px solid #d1d5db;
            font-size: 11px;
            color: #6b7280;
        }
    </style>
</head>
<body>
<div class="container">

    {{-- Header --}}
    <div class="header">
        <div class="header-logo">
            @if(!empty($logoDataUri))
                <img src="{{ $logoDataUri }}" alt="Logo">
            @endif
        </div>
        <div class="header-info">
            <div class="office-name">{{ $office->name }}</div>
            <div class="report-meta">Office Dashboard Report &nbsp;|&nbsp; {{ $startDate }} to {{ $endDate }}</div>
            <div class="report-meta">Generated on: {{ $generatedAt }}</div>
            <div class="report-meta">Generated by: {{ $generatedBy }}</div>
        </div>
    </div>

    {{-- KPI Summary --}}
    <div class="section">
        <div class="section-title">Summary Metrics</div>
        <div class="metrics-grid">
            <div class="metric-cell">
                <div class="metric-box">
                    <div class="metric-label">Total Documents</div>
                    <div class="metric-value">{{ $documentsUploaded }}</div>
                </div>
            </div>
            <div class="metric-cell">
                <div class="metric-box">
                    <div class="metric-label">Today's Documents</div>
                    <div class="metric-value">{{ $documentsUploadedToday }}</div>
                </div>
            </div>
            <div class="metric-cell">
                <div class="metric-box">
                    <div class="metric-label">Pending Workflows</div>
                    <div class="metric-value">{{ $pendingWorkflows }}</div>
                </div>
            </div>
            <div class="metric-cell">
                <div class="metric-box">
                    <div class="metric-label">Team Members</div>
                    <div class="metric-value">{{ count($officeMembers) }}</div>
                </div>
            </div>
        </div>
    </div>

    {{-- Workflow Statistics --}}
    @if(!empty($workflowStats))
    <div class="section">
        <div class="section-title">Workflow Statistics</div>
        <table>
            <thead>
                <tr>
                    <th>Metric</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody>
                @foreach($workflowStats as $key => $value)
                <tr>
                    <td>{{ ucwords(str_replace('_', ' ', $key)) }}</td>
                    <td>{{ $value }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endif

    {{-- Member Performance --}}
    @if(!empty($memberPerformanceMetrics))
    <div class="section">
        <div class="section-title">Member Performance</div>
        <table>
            <thead>
                <tr>
                    <th>Member</th>
                    <th>Uploads</th>
                    <th>Forwarded</th>
                    <th>Processed</th>
                    <th>Avg Response</th>
                    <th>Approval Rate</th>
                    <th>Score</th>
                </tr>
            </thead>
            <tbody>
                @foreach($memberPerformanceMetrics as $metric)
                <tr>
                    <td>{{ $metric['user']->first_name }} {{ $metric['user']->last_name }}</td>
                    <td>{{ $metric['uploads_count'] }}</td>
                    <td>{{ $metric['forwarded_count'] }}</td>
                    <td>{{ $metric['processed_count'] }}</td>
                    <td>{{ $metric['avg_response_time'] }}</td>
                    <td>{{ $metric['approval_rate'] }}%</td>
                    <td>{{ $metric['performance_score'] }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endif

    {{-- Team Members --}}
    <div class="section">
        <div class="section-title">Team Members</div>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                </tr>
            </thead>
            <tbody>
                @foreach($officeMembers as $member)
                <tr>
                    <td>{{ $member->first_name }} {{ $member->last_name }}</td>
                    <td>{{ $member->email }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="footer">
        <p>This report is automatically generated from the Document Archive System</p>
        <p>&copy; {{ date('Y') }} {{ $office->name }} – All rights reserved</p>
    </div>

</div>
</body>
</html>
